[prune]
  non-go = true
  unused-packages = true
  go-tests = true

# Branch is set here because kiln used to use submodules which leads dep to
# have a dirty working tree when it checks out master from a much older ref.
[[constraint]]
  name = "github.com/pivotal-cf/kiln"
  branch = "master"
