platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
inputs:
- name: om
run:
  path: "/bin/bash"
  args:
  - "-c"
  - |
    set -exu

    cwd="${PWD}"
    export GOPATH="$(pwd)/go"

    pushd "om" > /dev/null
      sed '/## Commands/q' README.md > /tmp/readme
      mv /tmp/readme README.md
      echo '```' >> README.md
      go run main.go --help >> README.md
      echo '```' >> README.md
      git config user.email "om-ci-bot@github.com.om"
      git config user.name "om-ci-bot"
      git add .
      git commit -m"Automatically updated README.md" || true
    popd > /dev/null

    cp -r $cwd/om $cwd/om-updated-readme
outputs:
- name: om-updated-readme